"""Tests for the LLM-backed title generator."""

from __future__ import annotations

import pytest

pytest.importorskip("fastapi")

from lovia import Agent  # noqa: E402
from lovia.web import create_app  # noqa: E402
from lovia.web.titles import _clean, _fallback_title, generate_title  # noqa: E402

from ..scripted_provider import ScriptedProvider, text  # noqa: E402


@pytest.mark.parametrize(
    "raw,expected",
    [
        ("Hello World", "Hello World"),
        ("  Hello World  ", "Hello World"),
        ('"Quoted Title"', "Quoted Title"),
        ("Title: Foo Bar", "Foo Bar"),
        ("title: foo bar.", "foo bar"),
        ("Line one\nLine two", "Line one"),
        ("Trailing punctuation!", "Trailing punctuation"),
        # Regression: a quoted title behind a "Title:" prefix must be fully
        # unwrapped — stripping quotes only once left a stray leading quote.
        ('Title: "Foo Bar"', "Foo Bar"),
        ('title: "hello world"', "hello world"),
        ('"Title: Foo Bar"', "Foo Bar"),
        ("Title: Title: Doubled", "Doubled"),
    ],
)
def test_clean(raw: str, expected: str) -> None:
    assert _clean(raw) == expected


def test_fallback_title_from_user_message() -> None:
    assert _fallback_title("How do I write a TCP server?") == (
        "How do I write a TCP server?"
    )
    assert _fallback_title("") == "New chat"


async def test_generate_title_uses_model_reply() -> None:
    provider = ScriptedProvider([text("Auth With OAuth2")])
    title = await generate_title(
        "How do I implement OAuth2 in FastAPI?",
        "Use fastapi-users with the OAuth backend…",
        model=provider,
    )
    assert title == "Auth With OAuth2"


async def test_generate_title_strips_decorations() -> None:
    provider = ScriptedProvider([text('"Title: Debugging A Memory Leak."')])
    title = await generate_title(
        "why is RSS climbing?", "look for cycles", model=provider
    )
    assert title == "Debugging A Memory Leak"


async def test_generate_title_fallback_on_blank_input() -> None:
    provider = ScriptedProvider([text("")])
    title = await generate_title("", None, model=provider)
    assert title == "New chat"


# ---- HTTP integration ------------------------------------------------------

from fastapi.testclient import TestClient  # noqa: E402


def test_chat_triggers_background_title_generation() -> None:
    # First entry is the chat reply; second is the title.
    provider = ScriptedProvider(
        [text("It depends on the language."), text("Programming Language Pick")]
    )
    app = create_app(Agent(name="bot", model=provider))
    c = TestClient(app)
    res = c.post(
        "/api/chat", json={"message": "Which programming language should I learn?"}
    )
    sid = res.json()["session_id"]

    # A new session gets a provisional title (the user's message) immediately;
    # the background task then refines it. Depending on whether that task has
    # run inside the TestClient's loop yet, either is valid.
    metas = c.get("/api/sessions").json()
    assert any(m["id"] == sid for m in metas)
    titled = next(m for m in metas if m["id"] == sid)
    assert titled["title"] in {
        "Which programming language should I learn?",  # provisional
        "Programming Language Pick",  # LLM-generated
    }


def test_stream_schedules_background_title() -> None:
    """The streaming path must schedule title generation as a background task.

    The title is *not* sent as an inline SSE event (that would block the
    stream from closing and keep the UI in a streaming state).  Instead,
    the background task stores the title in the DB and the client picks it up
    via a tight loadSessions() poll.
    """
    from .test_web import _parse_sse  # reuse SSE parser

    provider = ScriptedProvider([text("hello"), text("Greeting The User")])
    app = create_app(Agent(name="bot", model=provider))
    c = TestClient(app)
    with c.stream("POST", "/api/chat/stream", json={"message": "say hi"}) as res:
        body = "".join(res.iter_text())
    events = _parse_sse(body)
    kinds = [e[0] for e in events]

    # No inline title event — the title is generated by a background task.
    assert "title" not in kinds
    assert "done" in kinds

    sid = next(e[1]["session_id"] for e in events if e[0] == "session")
    metas = c.get("/api/sessions").json()
    titled = next(m for m in metas if m["id"] == sid)
    # Provisional title is set immediately; the background task may or may not
    # have refined it yet inside the test runner's loop, so accept either.
    assert titled["title"] in {"say hi", "Greeting The User"}


def test_new_session_gets_provisional_title_immediately() -> None:
    """Even with LLM title-gen disabled, a new session is never blank — the
    sidebar shows the user's first message until (if ever) a better title lands."""
    app = create_app(
        Agent(name="bot", model=ScriptedProvider([text("hi")])),
        generate_titles=False,
    )
    c = TestClient(app)
    sid = c.post(
        "/api/chat", json={"message": "How do I write a TCP server?"}
    ).json()["session_id"]
    metas = c.get("/api/sessions").json()
    titled = next(m for m in metas if m["id"] == sid)
    assert titled["title"] == "How do I write a TCP server?"
